site_name: Documentação UnbHub
theme:
  favicon: assets/logo.svg
  logo: assets/logo.svg
  name: material
nav:
  - Início: index.md
  - Releases:
    - Release 1: Releases/Release1.md
  - Análise de Requisitos: Requisitos.md
  - Arquitetura: Arquitetura.md
  - Protótipos: Prototipos.md
  - Reuniões:
      - Reunião 1: Reunioes/Reuniao1.md
      - Reunião 2: Reunioes/Reuniao2.md
      - Reunião 3: Reunioes/Reuniao3.md
      - Reunião 4: Reunioes/Reuniao4.md
      - Reunião 5: Reunioes/Reuniao5.md
      - Reunião 6: Reunioes/Reuniao6.md
      - Reunião 7: Reunioes/Reuniao7.md
      - Reunião 8: Reunioes/Reuniao8.md
      - Reunião 9: Reunioes/Reuniao9.md
      - Reunião 10: Reunioes/Reuniao10.md
      - Reunião 11: Reunioes/Reuniao11.md
      - Reunião 12: Reunioes/Reuniao12.md
      - Reunião 13: Reunioes/Reuniao13.md
      - Reunião 14: Reunioes/Reuniao14.md
      - Reunião 15: Reunioes/Reuniao15.md
      - Reunião 16: Reunioes/Reuniao16.md
      - Reunião 17: Reunioes/Reuniao17.md
      - Reunião 18: Reunioes/Reuniao18.md
      - Reunião 19: Reunioes/Reuniao19.md
      - Reunião 20: Reunioes/Reuniao20.md
      - Reunião 21: Reunioes/Reuniao21.md
      - Reunião 22: Reunioes/Reuniao22.md
      - Reunião 23: Reunioes/Reuniao23.md
  - Sprints:
      - Sprint 0: Sprints/Sprint0.md
      - Sprint 1: Sprints/Sprint1.md
      - Sprint 2: Sprints/Sprint2.md
      - Sprint 3: Sprints/Sprint3.md
      - Sprint 4: Sprints/Sprint4.md
      - Sprint 5: Sprints/Sprint5.md
      - Sprint 6: Sprints/Sprint6.md
      - Sprint 7: Sprints/Sprint7.md
      - Sprint 8: Sprints/Sprint8.md
      - Sprint 9: Sprints/Sprint9.md
      - Sprint 10: Sprints/Sprint10.md
      - Sprint 11: Sprints/Sprint11.md
      - Sprint 12: Sprints/Sprint12.md
  - Referências: Referencias.md


